config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cars#index"
  resources :cars do
    resources :reservations, only: %i[create new]
  end
  resources :reservations, only: %i[index show destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :reservations
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  def index
    if params[:q].present?
      @cars = Car.where("LOWER(brand) LIKE ?", "%" + params[:q].downcase + "%")
    else
      @cars = Car.all
    end
  end

  def show
    @car = Car.find(params[:id])
    @reservation =Reservation.new
    @user = @car.user
  end

  def new
    @car=Car.new
  end
  def create
    @car=Car.new(car_params)
    @car.user=current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end

  end
  def edit
    @car =Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end
  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path, notice: "Car has been destroyed!"
  end
  private
  def car_params
    params.require(:car).permit(:brand, :description, :price, :color, :mileage, :url_image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
    @sum = 0
  end
  def show
    @reservation = Reservation.find(params[:id])
    @start_time = @reservation.start_time
    @end_time = @reservation.end_time
    @car = @reservation.car
    @reservation.user = current_user
    if @start_time && @end_time
     @duration = (@end_time.to_date - @start_time.to_date).to_i
    end
  end

  def new
    @reservation = Reservation.new
    # @moto = Moto.find(params[:moto_id])
    # @reservation = Reservation.new(moto_id: @moto.id)
    # @reservations = @moto.reservations.order(:start_time)
  end

  def create
    @reservation = Reservation.new(
      start_time: params[:reservation][:start_time],
      end_time: params[:reservation][:end_time],
      car_id: params[:car_id]
    )
    @reservation.user = current_user
    redirect_to reservation_path(@reservation) if @reservation.save!
  end
  # this code dosent work
  # def new
  #   @reservation = Reservation.new
  #   @car = Car.find(params[:car_id])
  # end
  # def create
  #   @car = Car.find(params[:car_id])
  #   @reservation.user = current_user
  #   @reservation = Reservation.new(reservation_params)
  #   if @reservation.save
  #     redirect_to reservation_path(@reservation)
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end
  # private
  # def reservation_params
  #   params.require(:reservation).permit(:start_time, :end_time, :car_id)
  # end
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path, notice: "Reservation has been destroyed!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<div class="container">
  <%= simple_form_for(@car) do |f| %>
    <%= f.input :brand %>
    <%= f.input :description %>
    <%= f.input :color %>
    <%= f.input :price %>
    <%= f.input :mileage %>
    <%= f.input :url_image %>
    <%= f.submit 'Update', class: 'btn-edit' %>
  <% end %>
</div>

app/views/cars/index.html.erb
<div class="first-div">
  <form action="<%=cars_path%>" method="get">
  <div class="row height d-flex justify-content-center align-items-center">
    <div class="col-md-8">
      <div class="search">
        <i class="fa fa-search"></i>
        <input type="text" name="q" class="form-control" placeholder="Search">
        <button class="btn btn-primary">Search</button>
      </div>
    </div>
  </div>
  </form>
</div>
<div class="card-container">
  <%@cars.each do |car|  %>
    <div class="card" style="width: 18rem;">
        <img src="<%=car.url_image%>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= car.brand %></h5>
          <p class="card-text"><%= car.price %> MAD</p>
          <a href="<%=car_path(car)%>" class="btn btn-primary">See more</a>
        </div>
    </div>
  <%end  %>
</div>

app/views/cars/new.html.erb
<div class="container">
  <%= simple_form_for(@car) do |f| %>
    <%= f.input :brand %>
    <%= f.input :description %>
    <%= f.input :color %>
    <%= f.input :price %>
    <%= f.input :mileage %>
    <%= f.input :url_image %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="box">
  <div class="first-box">
    <img src="<%=@car.url_image%>" alt="">
    <h5><%= @user.first_name %> <%= @user.last_name %></h5>
    <h5>Brand: <%= @car.brand %></h5>
  </div>
  <div class="second-box">
    <div  class="small-box">
      <p>Price: </p>
      <p><%= @car.price %> dh/day</p>
    </div>
    <hr>
    <div class="small-box" >
      <p>Color:</p>
      <p><%= @car.color %></p>
    </div>
    <hr>
    <div class="small-box">
      <p>Mileage: </p>
      <p><%= @car.mileage %></p>
    </div>
    <hr>
    <div class="small-box">
      <p>Description: <%= @car.description %></p>
    </div>
  </div>
</div>

<%# <button class="booking">Book now</button> %>
<%= button_to "Delete", car_path(@car), method: :delete, form: { data: { turbo: true, turbo_confirm: "Are you sure?" } }, class:"delete-btn" %>
<%= link_to "Edit",edit_car_path(@car), class:"update-btn"%>
<div class="big-div" >
  <div class="div-reservation">
    <%= simple_form_for([@car, @reservation]) do |f| %>
    <div class="row">

        <%= f.input :start_time, as: :string,
                    wrapper_html: { class: "mb-4" },
                    label_html: { class: "form-label text-secondary fw-bold" },
                    input_html: { data: { controller: "flatpickr" } } %>


        <%= f.input :end_time, as: :string,
                    wrapper_html: { class: "mb-4" },
                    label_html: { class: "form-label text-secondary fw-bold" },
                    input_html: { data: { controller: "flatpickr" } } %>
        <%= f.submit "Book now", class:"home-submit" %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocCar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/index.html.erb
<div class="container">
  <%@reservations.each do|reservation| %>
  <br>
  <h2>Reservation <%= @sum += 1%></h1>
  <hr class="line">
  <h5>Brand: <%= reservation.car.brand %></h5>
  <% if reservation.start_time && reservation.end_time %>
  <h5>Price: <%= (reservation.car.price) * ((reservation.end_time.to_date - reservation.start_time.to_date).to_i)%> Dirhams</h5>
  <h5>From: <%= reservation.start_time %></h5>
  <h5>To: <%= reservation.end_time %></h5>
  <% end %>
  <%end  %>
</div>

app/views/reservations/show.html.erb
<div data-controller="popup">
  <div class="contain" data-popup-target="boxe">
    <div class="first">
      <div class="info-car">
        <img src="<%=@car.url_image%>" alt="">
        <h5>Brand: <%= @car.brand %></h5>
        <h5>Description: <%= @car.description %></h5>
        <h5>Price: <%= (@car.price)* @duration %> Dirhams</h5>
      </div>
    </div>
    <div class="reservation">
        <h2>Reservation for : </h2> <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
        <hr>
        <h5>From : <%= @reservation.start_time %></h5>
        <h5>To: <%= @reservation.end_time %></h5>
    </div>
  </div>
  <%= button_to "Delete", reservation_path(@reservation), method: :delete, form: { data: { turbo: true, turbo_confirm: "Are you sure?" } }, class:"delete-resa" %>
  <div class="confirm" data-popup-target="button">
    <button data-action="click->popup#display">Confirm Your Reservation</button>
  </div>

  <div class="popup" data-popup-target="pop">
    <img src="https://cdn.icon-icons.com/icons2/1506/PNG/512/emblemok_103757.png" >
    <h2>Thank you</h2>
    <p>Your reservation has been sent.</p>
    <p>For more information contact us 06000000.</p>
    <%= link_to "See all reservation", reservations_path, class:"style-btn" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to cars_path, class: "navbar-brand" do %>
      <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/07/13/22/1000_F_307132220_1dp9Lri0VE1LYu1ChDjtmGcTMMlIVOpN.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", cars_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Car", new_car_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://media.istockphoto.com/id/1337144146/fr/vectoriel/vecteur-dic%C3%B4ne-de-profil-davatar-par-d%C3%A9faut.jpg?s=170667a&w=0&k=20&c=o_wMhufXfqOtU-3qRd98jAgUFTAOmeJ_4jxH8yONUB0=", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create Car", new_car_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", reservations_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>